### ISSUE TITLE
Missing files

### ISSUE THREAD

**Issue by staminna** [daffl/mysam#11]
Hi

I cloned the main repo and tested v0.1.1 but when running mysam, a alert comes up saying 

"A Javascript error occured in the main process"

Uncaught Exception:
Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/mysam/db-data/actions'
    at Error (native)

and another one

Uncaught Exception:
Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/mysam/db-data/configuration'
    at Error (native)

Electron window still shows up, but the throbber spins indefinitely. 

Thanks.
Jorge.

**Comment by daffl** [comment]
This is probably the same problem as #9. The `/usr/local/lib/node_modules/mysam` folder needs to be writeable by the user that you start the application with. This won't be the case if you e.g. did `sudo npm install mysam -g`.

**Comment by staminna** [comment]
Thank you for quick reply! I thought installing as sudo would make harder for other users to run mysam.

so I did 
$ sudo npm install mysam -g
$ mysam -d

But it didn't seem to install all the dependencies correctly.

I can see
Hi. I am Sam...

terminal output: mysam:plugins Not loading plugin module /Users/jorgenunes/.npm-packages/lib +336ms
  mysam:plugins Not loading plugin module /Users/jorgenunes/.npm-packages/lib/node_modules/feathers +1ms
  mysam:plugins Not loading plugin module /Users/jorgenunes/.npm-packages/lib/node_modules/hotkeys +1ms
  mysam:plugins Not loading plugin module /Users/jorgenunes/.npm-packages/lib/node_modules/mysam +0ms
  mysam:plugins Found plugin mysam-weather +1ms
  mysam:plugins Setting up /Users/jorgenunes/.npm-packages/lib/node_modules/mysam-weather at /mysam-weather +1ms
  mysam:plugins Not loading plugin module , +1ms

console:
WARN: Could not find feathers in node_modules. Ignoring.
npm.js:358 WARN: Could not find socketio in node_modules. Ignoring.
npm.js:358 WARN: Could not find hotkeys in node_modules. Ignoring.
These packages exist and have Read & Write permissions to all users. They are installed globally and mysam knows they are there

After I type my name and hit Enter:
White page with "Cannot GET /?"

This must be because it can't find all required modules.

**Comment by daffl** [comment]
What I meant is that `sudo` shouldn't be used to either install or run it. Although, since it seems to load for you now, does it work without `-d`?

**Comment by staminna** [comment]
Right, sorry.
It sure does run without -d or sudo.

I can't see why is not loading all modules properly, and why is does the
weather plugin.
It looks like it's a permission issue.
Microphone connection is also broken in my environment.

**Comment by daffl** [comment]
If the microphone works in your browser it should work with the app as well. You can test it by going to [localhost:9090](http://localhost:9090) in your browser while the application is running.

The modules are either a permission or an installation issue. I will test a fresh installation on a VM to make sure the installation isn't busted for development mode and let you know if it worked.

**Comment by staminna** [comment]
Hi David.

Yes. The microphone icon flickers toggling on and off very quickly both in browser or Electron but the on the first listening toggle it holds a little longer and I managed to say 'storm'.
Hi 'undefined', here is what I can do.. said mySam.

mysam:plugins Not loading plugin module , +0ms
mysam:classifier Classifying +3m { input: 'storm' }
mysam:classifier { text: 'thank you', tags: [], action: { type: 'reply', reply: 'You\'re welcome' }, _id: 'cLCigspffa2jLeyY', id: '849c829d658baaeff512d766b0db3cce', input: 'storm', classifications:etc..

I did make sure to try chmod -R 777 /Users/../node_modules/*
and chown -R myusername /Users/../node_modules/*

but that of course didn't work out. perhaps I  should I try do this on every directory individually since the root?

Thank you for your help. I am very excited about this.

**Comment by daffl** [comment]
You'd probably have to run `sudo chmod -R 777 /Users/../node_modules/`. I'm not sure about your microphone setup but it seems like the browsers don't like working with it. Maybe try going through https://developers.google.com/web/updates/2013/01/Voice-Driven-Web-Apps-Introduction-to-the-Web-Speech-API?hl=en to find out what is happening with that.

From the log you sent me it now looks like using the `-d` is working though right?

**Comment by staminna** [comment]
Yes,  - d is working right indeed.
Will post as soon I can do it.

Thanks David.

**Comment by staminna** [comment]
The microphone code is correct, I just thought I had to press  Control + Space until I would finish the sentence. 
For some reason, mysam didn't catch my name in the beginning and it's not asking when I load sam. It does reply to hi ,help, shows options and knows the weather.

I have set chmod to 777 from my .npm-packages all the way up. I can't set this on my home directory as I believe it would be a security issue.

**Comment by daffl** [comment]
Ah yes, that should probably be mentioned in the documentation. Reinstalling should solve your name problem. In your case you could also run `rm /usr/local/lib/node_modules/mysam/db-data` to clear out the database and then it should ask again.

**Comment by staminna** [comment]
I have reinstalled without sudo, but the feathers, issue and socket.io still says
WARN: Could not find feathers in node_modules. Ignoring.
Perhaps that's why it's not catching my name

Hi undefined! Here is what I can do:

Say hi
Make a reply
Show the help
Call myplugin
Tell you the weather

Object {input: "George", text: "thank you", tags: Array[0], action: Object, _id: "wkdoUR6uXcgtN5j2"…}
can.js:262 Info: Model.js - Map created

**Comment by daffl** [comment]
No, that error has nothing to do with your problem. If you look at the training data at https://github.com/daffl/mysam-frontend/blob/master/lib/trainings.json#L85 you will see that it expects something along the lines of 

> "My name is..."

or

> "I'm ...".

I think we can close this issue and maybe you can create a new one to also try to fill in the name if the sentence is just a single word and not to save it when the name is empty? By the way, you can also type your name into the grey input field.
