### ISSUE TITLE
Missing lib/ folder

### ISSUE THREAD

**Issue by FliiFe** [daffl/mysam#14]
Hi.
First of all, sorry for being so invasive today.

When you clone the repo and try to test, lib/server is **not found**. In fact, it's not there.

(I had to copy it from the npm-created folder in */usr/lib/node_modules/mysam*)

**Comment by daffl** [comment]
Before starting the application you have to run `npm run compile` to transpile the source. If you make multiple changes you can also run `npm run compile:watch`.

**Comment by daffl** [comment]
I will add it to the docs today.

**Comment by FliiFe** [comment]
Oh, thanks. I don't think it's mentionned anywhere...

**Comment by daffl** [comment]
It is mentioned now at https://github.com/daffl/mysam#developing
