### ISSUE TITLE
install failed

### ISSUE THREAD

**Issue by forbeshawkins** [daffl/mysam#2]
Hi,

Very keen to try this out but I encountered the following error when attempting to install

npm ERR! Darwin 15.0.0
npm ERR! argv "node" "/usr/local/bin/npm" "install" "mysam" "-g"
npm ERR! node v0.12.5
npm ERR! npm  v2.11.2
npm ERR! code 128

npm ERR! Command failed: git clone --template=/Users/forbes/.npm/_git-remotes/_templates --mirror ssh://git@github.com/jeresig/jquery.hotkeys.git /Users/forbes/.npm/_git-remotes/ssh-git-github-com-jeresig-jquery-hotkeys-git-1383c260
npm ERR! Cloning into bare repository '/Users/forbes/.npm/_git-remotes/ssh-git-github-com-jeresig-jquery-hotkeys-git-1383c260'...
npm ERR! Warning: Permanently added the RSA host key for IP address '192.30.252.130' to the list of known hosts.
npm ERR! Permission denied (publickey).
npm ERR! fatal: Could not read from remote repository.

Attempted to sudo npm install but encountered the same error

thanks

**Comment by daffl** [comment]
Thank you! I just updated the frontend package and made a new release that uses HTTPS instead of git+ssh (which does indeed fail if not set up) for that dependency so it should work now.

**Comment by forbeshawkins** [comment]
Awesome. Works like a charm. Most impressive. Thanks!
