### ISSUE TITLE
MySam plugins file

### ISSUE THREAD

**Issue by thebergamo** [daffl/mysam#3]
Hi! This is an awesome project!

Is very helpful if we can see all plugins created for Sam in an file or a session in README.md!

Thanks and great work!

**Comment by daffl** [comment]
Thank you! The Readme does show a a short introduction how to create plugins at https://github.com/daffl/mysam#creating-plugins. I'd still like to record a video and create more detailed explanations about it as well. For now now the only other reference I can provide you is the existing weather plugin (https://github.com/daffl/mysam-weather).

Please let me know if you have any questions! Anything helps to provide more and better documentation.

**Comment by thebergamo** [comment]
If you can provide more documentation about creating plugins will be awesome =D
