### ISSUE TITLE
installation issue on linux debian

### ISSUE THREAD

**Issue by partizanos** [daffl/mysam#7]
This is the message I received: 
npm ERR! not a package /tmp/npm-3335-k0Xd4QqO/github.com/jeresig/jquery.hotkeys.git
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/mysam/node_modules/lodash'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  mysam@0.1.1 { [Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/mysam/node_modules/lodash']
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/mysam/node_modules/lodash' }
npm ERR! Error: ENOENT: no such file or directory, open '/tmp/npm-3335-k0Xd4QqO/github.com/jeresig/jquery.hotkeys.git-unpack/package.json'
npm ERR!     at Error (native)
npm ERR! If you need help, you may report this *entire* log,
npm ERR! including the npm and node versions, at:
npm ERR!     <http://github.com/npm/npm/issues>

npm ERR! System Linux 3.2.0-4-amd64
npm ERR! command "/usr/bin/nodejs" "/usr/bin/npm" "install" "mysam" "-g"
npm ERR! cwd /home/dimitris/downloads
npm ERR! node -v v4.2.1
npm ERR! npm -v 1.4.21
npm ERR! path /tmp/npm-3335-k0Xd4QqO/github.com/jeresig/jquery.hotkeys.git-unpack/package.json
npm ERR! syscall open
npm ERR! code ENOENT
npm ERR! errno -2
npm ERR! tar.unpack untar error /root/.npm/uberproto/1.1.2/package.tgz
npm ERR! tar.unpack untar error /root/.npm/feathers-commons/0.2.8/package.tgz
npm ERR! tar.unpack untar error /root/.npm/rubberduck/1.0.1/package.tgz
npm ERR! tar.unpack untar error /root/.npm/primus/3.2.3/package.tgz
npm ERR! tar.unpack untar error /root/.npm/lodash/2.4.2/package.tgz
npm ERR! tar.unpack untar error /root/.npm/mkdirp/0.5.0/package.tgz
npm ERR! tar.unpack untar error /root/.npm/async/0.9.0/package.tgz
npm ERR! tar.unpack untar error /root/.npm/nedb/1.2.1/package.tgz
npm ERR! tar.unpack untar error /root/.npm/yauzl/2.3.1/package.tgz
npm ERR! tar.unpack untar error /root/.npm/express/4.13.3/package.tgz
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/mysam/node_modules/feathers/node_modules/socket.io'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  feathers@1.1.1 { [Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/mysam/node_modules/feathers/node_modules/socket.io']
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/mysam/node_modules/feathers/node_modules/socket.io' }
npm ERR! tar.unpack untar error /root/.npm/primus-emitter/3.1.1/package.tgz
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/mysam/node_modules/feathers-nedb/node_modules/feathers-errors/node_modules/lodash'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  feathers-nedb@0.1.0 { [Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/mysam/node_modules/feathers-nedb/node_modules/feathers-errors/node_modules/lodash']
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/mysam/node_modules/feathers-nedb/node_modules/feathers-errors/node_modules/lodash' }
npm ERR! tar.unpack untar error /root/.npm/iconv-lite/0.4.12/package.tgz
npm ERR! tar.unpack untar error /root/.npm/uberproto/1.1.2/package.tgz
npm ERR! error rolling back Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/mysam/node_modules/natural-brain/node_modules/natural'
npm ERR! error rolling back     at Error (native)
npm ERR! error rolling back  natural-brain@0.2.0 { [Error: ENOTEMPTY: directory not empty, rmdir '/usr/local/lib/node_modules/mysam/node_modules/natural-brain/node_modules/natural']
npm ERR! error rolling back   errno: -39,
npm ERR! error rolling back   code: 'ENOTEMPTY',
npm ERR! error rolling back   syscall: 'rmdir',
npm ERR! error rolling back   path: '/usr/local/lib/node_modules/mysam/node_modules/natural-brain/node_modules/natural' }
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /home/myusername/downloads/npm-debug.log
npm ERR! not ok code 0

**Comment by daffl** [comment]
Could this be a permission issue? I'll give it a try on my Ubuntu VM and see if I can reproduce it. It looks like it was an issue with the hotkeys plugin, maybe I'll also just include it instead of installing it with NPM.

**Comment by daffl** [comment]
Thank you again for reporting the issue. I could reproduce it on my Ubuntu machine and change the frontend to include the module that caused the error instead of trying to install it. It worked for me now.

Please run `npm cache clean` and try installing again :)

**Comment by partizanos** [comment]
Ran great thanks a lot!
