### ISSUE TITLE
app doesn start 

### ISSUE THREAD

**Issue by partizanos** [daffl/mysam#9]
After writting mysam at terminal the window appears and two Javascript error occured in the main process appear 

Uncaught Exception:
Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/mysam/db-data/actions'
    at Error (native)

Uncaught Exception:
Error: ENOENT: no such file or directory, open '/usr/local/lib/node_modules/mysam/db-data/configuration'
    at Error (native)

after the app starts but it doesnt ask for the name as in demo video but it's infinitely waiting:

![mysam_bug](https://cloud.githubusercontent.com/assets/5407188/10776469/56fcf092-7d1a-11e5-8e0d-6e7cffc059dc.png)

**Comment by daffl** [comment]
This looks like a permission issue. Did you run `npm install mysam -g` with `sudo`? The user that is starting the application needs write permissions to the installation folder (in your case `/usr/local/lib/node_modules/mysam/`).

**Comment by daffl** [comment]
Closing this. Please reopen if there is still an issue.
